apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-server-deploy
  labels:
    name: chat-server-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      name: chat-server-pod
  template:
    metadata:
      labels:
        name: chat-server-pod
    spec:
      containers:
        - name: chat-server-container
          image: garvit3835/chat-server:latest
          ports:
            - containerPort: 5000