apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-server-deployment
  labels:
    name: chat-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: chat-server-pod
  template:
    metadata:
      labels:
        name: chat-server-pod
    spec:
      containers:
        - name: chat-server-container
          image: garvit3835/chat-server:2f4bedbad03fd807c5e5b8afe37e2aeb577a1ef2
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "1m"  # Request 10 milli CPUs (0.001 CPU cores)
            limits:
              cpu: "1m"  # Limit CPU usage to 1 milli CPU (0.001 CPU cores)

