apiVersion: v1
kind: Service
metadata:
  name: chat-server-service
spec:
  selector:
    name: chat-server-pod
  type: LoadBalancer #/NodePort/ClusterIP
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5000
      #nodePort: 30001