apiVersion: v1
kind: Service
metadata:
  name: chat-server-svc
spec:
  selector:
    name: chat-server-pod
  type: LoadBalancer #/NodePort/ClusterIP
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

      #nodePort: 30001