name: Node.js Chat Server CI/CD

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.12.2
      - run: npm install
      - run: npm test

  build-and-push-image:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.12.2
      - run: npm install
      - run: npm run build
      - name: Get Git commit hash
        id: commit_hash
        run: echo "::set-output name=commit_hash::$(git rev-parse --short HEAD)"
      - name: Get Git tag (if available)
        id: git_tag
        run: echo "::set-output name=git_tag::$(git describe --tags --abbrev=0 || echo 'latest')"
      - name: Create Docker image tag
        id: create_tag
        run: echo "::set-output name=image_tag::${{ steps.git_tag.outputs.git_tag }}-${{ steps.commit_hash.outputs.commit_hash }}"
      - run: docker build -t ${{ secrets.DOCKER_LOGIN }}/chat-server:${{ steps.create_tag.outputs.image_tag }} .
      - run: docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWORD }} 
      - run: docker push ${{ secrets.DOCKER_LOGIN }}/chat-server:${{ steps.create_tag.outputs.image_tag }}

  # deploy-to-aks:
  #   needs: build-and-push-image
  #   runs-on: ubuntu-latest    
  #   steps:
  #     - name: Checkout repository with clean cache
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  
  #     - name: Azure Kubernetes set context
  #       uses: Azure/aks-set-context@v1
  #       with:
  #         creds: '${{secrets.AZURE_CREDENTIALS}}'
  #         resource-group: venture_connect
  #         cluster-name: vc_cluster
  
  #     - name: Checkout repository
  #       uses: actions/checkout@v3
  #       with:
  #         ref: chat-server
        
  #     - name: Deploy to Kubernetes cluster
  #       uses: Azure/k8s-deploy@v1
  #       with:
  #         manifests: |
  #           k8s/deployment.yml
  #           k8s/service.yml
  #         images: '${{secrets.DOCKER_LOGIN}}/chat-server'
  #         action: deploy
  #         strategy: replace
  