name: Node.js Chat Server CI/CD

on:
  push:
    branches: 
      - main
    paths-ignore:
      - 'k8s'
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm test

  build-and-push-image:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    outputs:
      image-tag: ${{ steps.set_tag.outputs.image_tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm run build
      - name: Set image tag as environment variable
        id: set_tag
        run: echo "::set-output name=image_tag::${{ github.sha }}"
      - run: docker build -t ${{ secrets.DOCKER_LOGIN }}/chat-server:${{ steps.set_tag.outputs.image_tag }} .
      - run: docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push ${{ secrets.DOCKER_LOGIN }}/chat-server:${{ steps.set_tag.outputs.image_tag }}

  update-deployment:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Update deployment.yml
        run: sed -E -i "s/garvit3835\/chat-server:[a-zA-Z0-9]+/garvit3835\/chat-server:${{ needs.build-and-push-image.outputs.image-tag }}/g" k8s/deployment.yml

      - name: Stage changes
        run: git add k8s/deployment.yml

      - name: Set Git user identity
        run: |
          git config --global user.email "garvit3835@gmail.com"
          git config --global user.name "garvit3835"
    
      - name: Commit changes
        run: git commit -m "Update deployment.yml" k8s/deployment.yml
  
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main


  # deploy-to-aks:
  #   needs: build-and-push-image
  #   runs-on: ubuntu-latest    
  #   steps:
  #     - name: Checkout repository with clean cache
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  
  #     - name: Azure Kubernetes set context
  #       uses: Azure/aks-set-context@v1
  #       with:
  #         creds: '${{secrets.AZURE_CREDENTIALS}}'
  #         resource-group: venture_connect
  #         cluster-name: vc_cluster
  
  #     - name: Checkout repository
  #       uses: actions/checkout@v3
  #       with:
  #         ref: chat-server
        
  #     - name: Deploy to Kubernetes cluster
  #       uses: Azure/k8s-deploy@v1
  #       with:
  #         manifests: |
  #           k8s/deployment.yml
  #           k8s/service.yml
  #         images: '${{secrets.DOCKER_LOGIN}}/chat-server'
  #         action: deploy
  #         strategy: replace
  