name: Node.js Chat Server CI/CD

on:
  push:
    branches: [chat-server]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./chat-server
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.12.2
      - run: npm install
      - run: npm test
      - name: Revert code on test failure
        if: failure()
        run: |
          git reset --hard HEAD^
  build-and-push-image:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: docker build -t garvit3835/chat-server .
      - run: docker login -u garvit3835 -p $DOCKER_PASSWORD
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push garvit3835/chat-server

  deploy-to-kubernetes:
    needs: build-and-push-image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-kubectl@v2.0
      - run: kubectl apply -f k8s
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
